version = 1
name = "Obsidian to Anki"

[setup]
script = "echo No setup required"

[[actions]]
name = "Run GUI"
icon = "run"
command = "python3 -m obsidian_to_anki"

[[actions]]
name = "Run Tests"
icon = "test"
command = "python3 -m unittest discover -s tests -q"
